### ISSUE TITLE
throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");

### ISSUE THREAD

**Issue by minnaq** [paulxuca/react-router-redux-saga-4#2]
Listening to http://localhost:3000
loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
/Users/tim/Documents/work/me/github/react-router-redux-saga-4/node_modules/loader-runner/lib/loadLoader.js:35
			throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");
			^

Error: Module '/Users/tim/Documents/work/me/github/react-router-redux-saga-4/node_modules/react-router/index.js' is not a loader (must have normal or pitch function)
    at loadLoader (/Users/tim/Documents/work/me/github/react-router-redux-saga-4/node_modules/loader-runner/lib/loadLoader.js:35:10)
    at iteratePitchingLoaders (/Users/tim/Documents/work/me/github/react-router-redux-saga-4/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/tim/Documents/work/me/github/react-router-redux-saga-4/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/tim/Documents/work/me/github/react-router-redux-saga-4/node_modules/webpack/lib/NormalModule.js:129:2)
    at NormalModule.build (/Users/tim/Documents/work/me/github/react-router-redux-saga-4/node_modules/webpack/lib/NormalModule.js:180:15)
    at Compilation.buildModule (/Users/tim/Documents/work/me/github/react-router-redux-saga-4/node_modules/webpack/lib/Compilation.js:142:10)
    at factoryCallback (/Users/tim/Documents/work/me/github/react-router-redux-saga-4/node_modules/webpack/lib/Compilation.js:324:11)
    at /Users/tim/Documents/work/me/github/react-router-redux-saga-4/node_modules/webpack/lib/NormalModuleFactory.js:242:4
    at /Users/tim/Documents/work/me/github/react-router-redux-saga-4/node_modules/webpack/lib/NormalModuleFactory.js:93:13
    at /Users/tim/Documents/work/me/github/react-router-redux-saga-4/node_modules/tapable/lib/Tapable.js:204:11
    at NormalModuleFactory.<anonymous> (/Users/tim/Documents/work/me/github/react-router-redux-saga-4/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/tim/Documents/work/me/github/react-router-redux-saga-4/node_modules/tapable/lib/Tapable.js:208:13)
    at onDoneResolving (/Users/tim/Documents/work/me/github/react-router-redux-saga-4/node_modules/webpack/lib/NormalModuleFactory.js:68:11)
    at onDoneResolving (/Users/tim/Documents/work/me/github/react-router-redux-saga-4/node_modules/webpack/lib/NormalModuleFactory.js:189:6)
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)

**Comment by venkatb4u** [comment]
Yes,I get the same error as well.

**Comment by lielran** [comment]
same as here

**Comment by aheintz** [comment]
Yep, same here.

**Comment by RaedShari** [comment]
same
